# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62c1251800af92bb48b7f0925b7d243cbbba6b91456ef002f10450857c2212fe0b6f4a675c6f0b494591181489f761ffc1560a7774e1a8daff058cb4f03c37f3

test:
  secret_key_base: f821b0b8d1ce6b41f3e1b4bf412151d01cd16b5db919505d35b3ce8f66929aac5049fad5668604f05bde0923c97a7873ce447a16f33bfac8308c0974dcfe62a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
